In [2]:
import random
import numpy as np
import pandas as pd

with open("names.txt",encoding="utf-8") as file:
    content = file.read()

names_list = content.split()
names = random.choices(names_list,k=50)

with open("names.txt",encoding="utf-8") as file:
    content = file.read()
    
scores = np.random.randint(50,101,size=(50,5))
student_df = pd.DataFrame(scores,
             columns=['國文','英文','數學','地理','歷史'],
             index=names)
student_df

     國文   英文  數學   地理   歷史
謝哲維  74   82  61   68   95
張慧君  76   70  60   62   54
賴佳雯  83   51  61   50   86
劉雯芬  65   97  98   74   83
李佳彥  59   75  53   52   66
柯韋成  56   78  99   84   95
劉昀天  93   97  81   72   85
朱士弘  99   87  67   89   52
黎惠雯  58   97  72   64   71
陳家維  59   87  88   71   86
楊韋廷  65   94  89   58   95
林志喜  71   68  86   57   70
許淑婷  95   88  52   98   83
林怡偉  82   82  98   92   84
蘇婷婷  84   80  89   59   54
蔡孟泉  73   75  59   99  100
黃奎紹  53   93  70   57   70
傅佳琳  59   72  85   95   52
楊健麟  90   88  84   98   82
高智超  79   65  96   75   77
林群清  81   75  52   94   62
臧怡君  86   59  54   94   57
盧冠發  97   84  94   78   95
葉軍仰  97   85  92   83   71
林珍旺  78   59  50   60   75
黃必琪  83   65  80   61   71
藍哲嘉  96   73  52   91   79
翁均安  98   96  71   70   70
陳建豪  56   90  78   71   86
周家銘  59   52  69   83   93
林清英  52   57  79  100   60
彭虹屏  93   69  86   58   68
李政成  60   58  62   64   62
張莉雯  75   77  74   54   56
黃江旭  90  100  87   81   56
黃必琪  74   87  50   75   87
林麗萍  91   75  53   64   87
錢欣潔  54   75  90   50   79
張婕妤  67   74  80   80   76
盧冠發  58   83  73   94   96
林瑞喬  59   81  86   94   57
蘇凡菁  78   78  82   60   76
方雅慧  73  100  77   76   96
張天亨  71   57  63   74   73
劉旭士  67   52  67   89   82
翁鈺婷  81   70  84   90   59
魏秋萍  81   73  83   59   88
彭茹靖  67   63  82   88   68
蔡偉成  55   71  60   62   70
張嘉韋  67   55  59   52   69

In [4]:
#欄和列的選取
student_df['國文']
student_df[['國文','英文']]

     國文   英文
謝哲維  74   82
張慧君  76   70
賴佳雯  83   51
劉雯芬  65   97
李佳彥  59   75
柯韋成  56   78
劉昀天  93   97
朱士弘  99   87
黎惠雯  58   97
陳家維  59   87
楊韋廷  65   94
林志喜  71   68
許淑婷  95   88
林怡偉  82   82
蘇婷婷  84   80
蔡孟泉  73   75
黃奎紹  53   93
傅佳琳  59   72
楊健麟  90   88
高智超  79   65
林群清  81   75
臧怡君  86   59
盧冠發  97   84
葉軍仰  97   85
林珍旺  78   59
黃必琪  83   65
藍哲嘉  96   73
翁均安  98   96
陳建豪  56   90
周家銘  59   52
林清英  52   57
彭虹屏  93   69
李政成  60   58
張莉雯  75   77
黃江旭  90  100
黃必琪  74   87
林麗萍  91   75
錢欣潔  54   75
張婕妤  67   74
盧冠發  58   83
林瑞喬  59   81
蘇凡菁  78   78
方雅慧  73  100
張天亨  71   57
劉旭士  67   52
翁鈺婷  81   70
魏秋萍  81   73
彭茹靖  67   63
蔡偉成  55   71
張嘉韋  67   55

In [6]:
student_df.loc['謝哲維']
student_df.loc[['謝哲維','張嘉韋']]

     國文  英文  數學  地理  歷史
謝哲維  74  82  61  68  95
張嘉韋  67  55  59  52  69

In [10]:
student_df.iloc[0]
student_df.iloc[[0,49]]
student_df.iloc[:5]
student_df.iloc[-5:]

     國文  英文  數學  地理  歷史
翁鈺婷  81  70  84  90  59
魏秋萍  81  73  83  59  88
彭茹靖  67  63  82  88  68
蔡偉成  55  71  60  62  70
張嘉韋  67  55  59  52  69

In [11]:
student_df.iloc[-5:,:3]

     國文  英文  數學
翁鈺婷  81  70  84
魏秋萍  81  73  83
彭茹靖  67  63  82
蔡偉成  55  71  60
張嘉韋  67  55  59

In [14]:
#值的選取
student_df[student_df['地理'] < 60]

     國文  英文  數學  地理  歷史
賴佳雯  83  51  61  50  86
李佳彥  59  75  53  52  66
楊韋廷  65  94  89  58  95
林志喜  71  68  86  57  70
蘇婷婷  84  80  89  59  54
黃奎紹  53  93  70  57  70
彭虹屏  93  69  86  58  68
張莉雯  75  77  74  54  56
錢欣潔  54  75  90  50  79
魏秋萍  81  73  83  59  88
張嘉韋  67  55  59  52  69

In [15]:
student_df[student_df['國文'] < 60]

     國文  英文  數學   地理  歷史
李佳彥  59  75  53   52  66
柯韋成  56  78  99   84  95
黎惠雯  58  97  72   64  71
陳家維  59  87  88   71  86
黃奎紹  53  93  70   57  70
傅佳琳  59  72  85   95  52
陳建豪  56  90  78   71  86
周家銘  59  52  69   83  93
林清英  52  57  79  100  60
錢欣潔  54  75  90   50  79
盧冠發  58  83  73   94  96
林瑞喬  59  81  86   94  57
蔡偉成  55  71  60   62  70

In [19]:
#地理和國文同時不及格的
student_df[(student_df['地理'] < 60) & (student_df['國文'] < 60)]

     國文  英文  數學  地理  歷史
李佳彥  59  75  53  52  66
黃奎紹  53  93  70  57  70
錢欣潔  54  75  90  50  79

In [20]:
#地理和國文同時不及格的
student_df[(student_df['地理'] < 60) | (student_df['國文'] < 60)]

     國文  英文  數學   地理  歷史
賴佳雯  83  51  61   50  86
李佳彥  59  75  53   52  66
柯韋成  56  78  99   84  95
黎惠雯  58  97  72   64  71
陳家維  59  87  88   71  86
楊韋廷  65  94  89   58  95
林志喜  71  68  86   57  70
蘇婷婷  84  80  89   59  54
黃奎紹  53  93  70   57  70
傅佳琳  59  72  85   95  52
陳建豪  56  90  78   71  86
周家銘  59  52  69   83  93
林清英  52  57  79  100  60
彭虹屏  93  69  86   58  68
張莉雯  75  77  74   54  56
錢欣潔  54  75  90   50  79
盧冠發  58  83  73   94  96
林瑞喬  59  81  86   94  57
魏秋萍  81  73  83   59  88
蔡偉成  55  71  60   62  70
張嘉韋  67  55  59   52  69